require 'spree_core'
require 'spree/core/mail_interceptor'
require 'spree/core/mail_method'
require 'spree/core/mail_settings'
require 'spree_mail_settings/engine'
require 'spree_mail_settings/version'
